name: example
description: An example app to show the use of Animation Text Kit.

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
      sdk: flutter
  geolocator: 7.0.0
  cupertino_icons: ^1.0.0
  path: 1.8.0
  english_words: ^4.0.0
  animated_text_kit: ^4.2.1
  introduction_screen: ^2.1.0
  qr_flutter: ^4.0.0
  flutter_sound:
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  build_web_compilers: 2.12.0
  pedantic: ^1.11.0

analyzer:
  errors:
    undefined_prefixed_name: ignore

flutter:
  uses-material-design: true
